### ISSUE TITLE
`GeoInterface.geometrycolumns`

### ISSUE THREAD

**Issue by rafaqz** [javierbarbero/SpatialDependence.jl#4]
This package looks great!

I was just reading the code and notice your geometry column handling. GeoInterface is defaulting to `:geometry` as the geometry column, but also has a `geometrycolumns` method, than can be overidden for specific tables. If you just need one column you take the first one. By default that will be `:geometry`.

Some packages like [GADM](https://github.com/JuliaGeo/GADM.jl/issues/50) are still using `:geom` but we should try to move everything to `:geometry` or using the `getometrycolumns` method if its different so things are standardised.

Cheers, carry on

**Comment by javierbarbero** [comment]
Thank you for pointing me to the `geometrycolumns` method. This is great. I will make the necessary code changes. The more standardized, the better.

Best.
